/**
 * History page snapshot suite (E10-S4 / D24, #241).
 *
 * The history page is pure REST (`GET /api/roasts`) — no SSE, no replay
 * stepping — so both states are made deterministic with a Playwright route
 * intercept of `/api/roasts` rather than depending on whatever runs the replay
 * store happens to hold. This keeps the committed PNG baselines stable and
 * decoupled from the fixture's run count.
 *
 * Two required states (kickoff §5): `history` (a populated table) and
 * `history-empty` (the first-run empty state). DOM-chrome `toHaveScreenshot()`;
 * there is no canvas on this page, so nothing is masked.
 *
 * #241 — why the populated baseline went stale-blind: the route intercept works
 * fine (the data IS mocked), but the committed `history-linux.png` was last
 * regenerated at #114 (5 columns) and never refreshed after #181 added the
 * Advisor column or #111 the FC column. Adding two narrow, lightly-inked columns
 * to a `w-full` table moved fewer pixels than `maxDiffPixelRatio` allowed, so the
 * gate passed against the stale image AND `--update-snapshots` (Playwright 1.55
 * only rewrites a snapshot whose comparison FAILS) left it untouched. The fix:
 * (1) the fixture below is typed to the full `RoastSummary` contract so every
 * column — including the previously-omitted advisor_* fields — renders real
 * content a dropped column would visibly change; (2) an explicit header-cell
 * structural assertion fails fast (not just on pixels) if a column is added or
 * removed; (3) the baseline was regenerated by DELETING it first so the pinned
 * image captured the true 7-column render (a no-diff `--update-snapshots` would
 * not have).
 */

import { expect, test, type Page } from "@playwright/test";

import type { RoastSummary } from "../../src/lib/types";

// The seven columns the history table renders, in order (HistoryTable.tsx). The
// populated-state test asserts the live header row matches this EXACTLY, so a
// column added or dropped fails structurally even if the pixel diff stays under
// tolerance — closing the #241 blind spot at the DOM layer, not just the image.
const EXPECTED_COLUMNS = ["Date", "Bean", "Outcome", "Advisor", "FC", "Dev %", "Rating"] as const;

// A fixed, hand-authored history payload typed to the FULL `RoastSummary`
// contract (web/src/lib/types.ts) so the snapshot exercises EVERY populated
// column, not a degenerate state. It deliberately spans:
//   - every outcome badge (completed / aborted / faulted);
//   - a rated + an unrated run, and a null dev %;
//   - (#111) an FC time AND a run that never reached first crack (`null`);
//   - (#184) the three distinct Advisor-cell states — consults with a clamp +
//     reject, consults "all allowed", and zero consults ("no advice").
// The advisor_* fields are REQUIRED by `RoastSummary`; the prior fixture omitted
// them, so the Advisor cell rendered from `undefined` and the column tested
// nothing. Typing `HISTORY` to the contract makes a future field rename a
// compile error here rather than a silently-blank column.
const HISTORY: { runs: RoastSummary[] } = {
  runs: [
    {
      id: "run-a",
      started_at_utc: "2026-06-07T14:00:00Z",
      completed_at_utc: "2026-06-07T14:12:00Z",
      first_crack_at_utc: "2026-06-07T14:09:00Z",
      agent_phase: "complete",
      outcome: "completed",
      bean_origin: "Ethiopian Yirgacheffe",
      bean_varietal: "Medium",
      rating: 5,
      development_percent: 19,
      advisor_consults: 24,
      advisor_clamped: 3,
      advisor_rejected: 1,
      advisor_failed: 0,
    },
    {
      id: "run-b",
      started_at_utc: "2026-06-06T15:07:00Z",
      completed_at_utc: "2026-06-06T15:18:00Z",
      first_crack_at_utc: "2026-06-06T15:15:00Z",
      agent_phase: "complete",
      outcome: "aborted",
      bean_origin: "Colombian Supremo",
      bean_varietal: "Dark",
      rating: 2,
      development_percent: 21,
      advisor_consults: 11,
      advisor_clamped: 0,
      advisor_rejected: 0,
      advisor_failed: 0,
    },
    {
      id: "run-c",
      started_at_utc: "2026-06-05T16:14:00Z",
      completed_at_utc: "2026-06-05T16:21:00Z",
      first_crack_at_utc: null,
      agent_phase: "faulted",
      outcome: "faulted",
      bean_origin: "Kenyan AA",
      bean_varietal: null,
      rating: null,
      development_percent: null,
      advisor_consults: 0,
      advisor_clamped: 0,
      advisor_rejected: 0,
      advisor_failed: 0,
    },
  ],
};

async function mockHistory(page: Page, body: unknown): Promise<void> {
  await page.route("**/api/roasts", (route) =>
    route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify(body),
    }),
  );
}

async function settle(page: Page): Promise<void> {
  await page.evaluate(() => document.fonts.ready);
}

test("history — populated table", async ({ page }) => {
  await mockHistory(page, HISTORY);
  await page.goto("/roasts");
  await expect(page.getByTestId("history-table")).toBeVisible();
  await expect(page.getByTestId("history-row")).toHaveCount(3);
  // Structural guard (#241): the rendered header row must match the contract's
  // seven columns exactly. This fails fast on an added/removed/reordered column
  // even when the pixel diff stays under tolerance — the gap that left the
  // populated baseline blind to the Advisor (#181) and FC (#111) columns. Scoped
  // to the history table's own `thead` (not a page-global `thead th`) so a second
  // table on the page could never make this assertion match the wrong header row.
  await expect(page.locator("[data-testid='history-table'] thead th")).toHaveText([
    ...EXPECTED_COLUMNS,
  ]);
  await settle(page);
  await expect(page).toHaveScreenshot("history.png");
});

test("history-empty — first-run empty state", async ({ page }) => {
  await mockHistory(page, { runs: [] });
  await page.goto("/roasts");
  await expect(page.getByTestId("history-empty")).toBeVisible();
  await settle(page);
  await expect(page).toHaveScreenshot("history-empty.png");
});
